#+title: Connections
I can hear gunshots firing outside, bursting like the fizz off a freshly opened soda, and I just hope they don’t kill me before Brad is done telling me about how his kids weren’t growing up like we did, how they were lazy and privileged. I half-heartedly nod at all the right pauses in his diatribe, waiting for my opportunity to speak—this is closer than I had gotten to my goal in two decades. A silence opens itself in Brad’s speech, as he pauses to contemplate the level to which he may have contributed to the rot in the next generation’s brains with the example he set.

“Do you remember Sarah?” I say, but just as the words make their way out of me a sound like a sock being sucked up by a vacuum clears the air, and suddenly we are in a million pieces, spreading over the eastern front of the battlefield.

“Shit,” I hear Brad say, “We should focus up next round, I didn’t hear that one coming.”

“Yeah,” I say, wondering how many more lifetimes I’ll have to live before I get another chance to speak. “Find me quickly,” I try to say, but don’t think they manage to get out. I was never good at the extra-mental articulations of the chat activator.
I can’t see Brad, through the atomized firestorm. Both our in-game bodies had been disintegrated, but we’d find ourselves in new ones before long, once the sim-engine found suitable hosts.

“Sorry, didn’t catch that. See you on the other side.” Brad’s voice fades away, as does the light and sound of the battlefield. I think about unplugging, but my body was probably still hard at work, and becoming cognizant to the labor I’d sold myself into for this chance seemed worse than enduring it for a little longer.

#

I woke up in a twin bed, head ringing, and for a moment forgot my name. Who was Brad? He had seemed important a second ago. Now all memories from the dream were fading, even as I tried desperately to hang onto them.

“Breakfast is ready!” I heard a voice call from downstairs. I rubbed by palms into my eyes until splotches of colors began to form, then got ready for the day.

All day at school, I had a funny feeling of deja vu, and every conversation I had I was just following a script—my mind drifted above it all, not getting involved.

I had forgotten that it was job fair day, and all my friends had grouped up at the SimPharm table, asking what the best extracurriculars were to get in on the latest playtest. No other career had the same draw that SimPharm had, and none of the teachers dared argue, not when SimPharm gave kids a chance at a better life than their financial situation and scholastic achievements would merit. And to the kids, the movies and TV shows about SimPharm were hard not to be drawn in by. They made ‘engineer’ take on a completely new meaning. In the media, being a SinPharm tech was like being a secret agent, a scientist, and a baseball player all in one. What kid wouldn’t want to join up? I avoided the line, seeing Steven, the long haired punkish kid I’d had a fight with last weekend, and walked around aimlessly.

“So were you saying something?” A boy my age said to me, out of nowhere.

“Excuse me?” I asked.

“You mentioned Sarah, you meant your sister, right?” He said, looking around the room for something, not making eye contact.

“Sorry, I think you have the wrong person.” I said.

He cocked his head, examining the marine corp table from afar. “Oh, sorry, forgot you take a while to come to. Probably wasn’t important anyway. Listen. We’ll beat those bastards this time. I’mm thinking Air Force. But the training takes too long… Maybe there’s a trick to speeding it up, I haven’t really tried before, usually just go on auto till duty calls. Maybe I’ll have better luck if I put in some time doing it manually. Call me when you get a grip.”

He hands me a piece of paper with a phone number on it. I’m not sure what’s going on, so I pocket it, then go to the bathroom to wash my face.

As soon as I close the door to the mens room, a sharp flash washes over me. I hear voices and music from the gymnasium on the other side of the door, I feel removed from them. The physical space warps, the gym is both inches and lightyears away simultaneously. The void between the two rooms is an entity of time, too; everything is ancient, thousands of thousands of years old. I remember Sarah. I realize I missed the chance I’d waited for and smash a mirror with my fist. I don’t feel the pain as the blood gushes out of my knuckles.

Activators. Thats what SimPharm called them. Like the hand gestures used to articulate pers-coms but done completely in the mind. Most people that were plugged in were masters of them, maneuvered their brains like they were simply pressing buttons—it was reflex, second nature. I had never been into the idea of escaping to another life, the one I had was too demanding, and I didn’t have the cash anyway. As my memories flooded back, they mixed with the artificial memories of the kid whose body I’d taken. Kyle. I knew he was a simulation, but I felt bad for him, felt embarrassed as I passed over the memories of crushes and rivals; standard high school kid stuff, but when it felt like it was really you, it became more than just randomly seeded programming. I didn’t understand why this was necessary for the sim-engine, it felt like I had stolen something. I still didn’t know what the activator was supposed to be for gaining awareness once transferred to a new body, but for me it always happened accidentally, and always in the same situation: I had to be in a room, preferably a bathroom, while there was the noise of a gathering just outside the door. Once it had been a bedroom at a house party. Another time, the port-a-potty at a concert. The worst was when I had somehow stayed ignorant all the way up to when the battles started—the game seemed to have a safety features where it automatically removed the auto-pilot once the intended game-scenes began. This time, it happened by chance blessedly early. I had time.

I burst out of the bathroom, trying to remember the face of the body Brad had been placed in, looking for it in the crowd of high schoolers wearing name tags and dress clothes still laid with creases left from the racks they were plucked from. There was no sign of him, but I remembered what he had said about the Air Force. I raced over to the booth and signed up, ignoring almost everything the man said to me, just nodding politely. The game was pretty forgiving about the social interactions you had with the simulated characters—but every eye was also a camera, and your overall sociability score was shared to your account after you left. My job would be in jeopardy if I displayed too much antisocial behavior—I couldn’t worry about that now, I had to find Brad.

#

“I thought you worked in bionics?” Doctor Singer had said, when I proposed my plan. “I’d have imagined you knew how DivInt works.”

"Actually," I said, "you'd be surprised how little the engineering work for augments has to do with the end result. I've never seen one of the eye-cam's I code for, let alone use one. Wouldn't know what to do with it if I was given the chance, to be honest."

I had thought that tidbit funny, but I could tell my the flat line of Dr. Singer's lips that she felt I was distracting from the point of our talk.

“I see that you’re old fashioned, and I can appreciate that. I still like to see clients this way.” She said, waving her pointer finger between the two of us. “But really, for nuanced interactions like this, your meaning and intention are much more likely to get through in the subliminal.  I’d spend a few days thinking about him, make sure your Second Self knows how much you want to reach out, and it’ll happen without you needing to lift a finger.”

"I understand that, but I'd like to talk to Brad myself. Ask him myself. It seems like the right thing to do."

She smiled and I tried to read her feelings though the white of her teeth. Disinterest, mostly, but also some shame, or anger, though I wasn’t sure why those would be there. I thanked her and left, mind unchanged.

What I didn't tell her, was that I didn't know if I could pull off the subliminal operation even if I wanted too. Yes, I did work in bionics, but just as a mid level engineer. I wasn’t low enough to need to turn zombie, but wasn’t high enough to be able to afford a decent Second Self processor. So I lived what friends and family thought to be a quant life of an older time: I lived through every second of my life at work, fully aware, and then went home and read books or watched old entertainment programs. When I did plug in, it was usually to check for updates to my relationships. I couldn’t process many with the little server that I kept hidden in the storage closet of my tiny prefab apartment--a hand-me-down from Sarah--but it was enough to keep track of mom, my cousins, and a few college buddies. Brad was one of those. He and Sarah had dated sophomore year. We used to all hang out at a local bar where her band played. He let me pretend that his friends were my friends, they were always genuinely nice to me. Now Sarah was dead, and I felt like I didn’t even know how to tell the world about it.

'After Image' was what Dr. Singer called it, the way Sarah was stuck in the net. Or not Sarah, not really, but her digital version. Usually, when someone died, it was up to their next of kin to shut down their Second Self, which would go on maintaining relationships like a ghost until properly exorcised. With modern Second Self processors, all of that would be taken care of automatically. But since she was unlucky enough to have me as her next of kin, that hadn't happened. I had thought I could just turn the server off, but according to Doctor Singer, that would cause unintended trauma on those who were in her inner circle. She was an Arti-facer, payed third-party devs that do repair and consultation for SimPharm products. She said that those too closely connected to an improperly disposed of Second Self could become depressed, unproductive, and I didn’t have the money to pay the corpos that would come asking for compensation. But the only way to turn off a Second Self was from the inside. And mine was basically a derelict. I had never been interested in learning all the activators, all the arcane uses of the inner logic of my brain. And so I was locked out of the after image of my twin sister, watching her send ‘happy birthday’ and ‘get well soon’ messages to acquaintances as if she were still alive. That meant I had to find someone to do it for me, and the only way to do it without paying a crazy fine for an infiltrator was to get someone who knew what they were doing, and who was close enough to her to be able to get inside. Brad was the only one I knew, so I wanted to ask. The way things typically go, these kinds of questions would be asked without the person even knowing it. The Second Self would simulate the decision making process, and if yes, then he would wake up feeling like we had already had the conversation, and he’d do it without ever needing to say ‘hello’ to me.

I didn’t want that. I wanted to speak to him, to ask him myself—I’m not sure why. It just seemed like the right thing to do. Everyone else told me otherwise. I spent weeks trying to manifest a rekindling connection with him with what little computation power my Second Self had. Finally, I was able to get an invite to hang out. He and his (our) college buddies had a standing time every weekend to play SimPharm’s latest competitive simulation strategy game, WarBonds. I had never played sim-games, but I needed to get a moment alone with Brad, so I accepted the invite.

Then I learned about the processing requirements for the game. There was no way my tiny Mirai-kon would be able to handle it. I asked Dr Singer for advice, even though she took every chance she could to sigh and huff in shows of defeat and exhaustion with me.

“Well,” she said, splaying her arms out in a show of helplessness, “there’s always the Sleeper Comps.”

“Become a Zombie?” I said. I shook my head, unable to think of a better idea. “Aren’t those things a scam anyway? I heard that once you start, you never get out of debt to be able to leave—and thats if your body doesn’t crap out on you.”

“It's not glamourous, I won't lie about that. But you're well educated, and seem naturally precautious. Just stay away from the gambling ads and you'll be ok.”

“You mean like the ones they blast into your brains the entire time you’re under?”

“Let’s not delve into conspiracy, Mr. Strand.” She said with an ironic tone.

“Right. Well if it’s the only thing I can do.”

“It’s not too late to do things the more conventional way. Relationships are much better handled by computers, there’s too much room for misinterpretation without them.”

Unconventional. I remembered Sarah using that word to describe me, but I couldn’t remember the context.

“I’ll use a Sleeper,” I said, “Where can I find one on short notice?”

That was twenty lifetimes ago. Time moves differently here. Especially with the added juice from the rental EX-Wraith I got in the Sleeper Comp deal. There’s an activator I can use to tab out of the game, and check the time—but like all the others, I don’t know how to do it. Instead, my only glimpses at the outside world are between matches, when the game resets the simulation. Before I became Kyle, the screen told me it was two the afternoon, about three hours after we started. I don’t know how people do it. Spend their weekends living through millennia upon millennia of torturous battles and agonizing mental and emotional labor. Every time I come into contact with Brad, I try to talk to him. And every time, there’s a bomb exploding, or a sniper on our flank. But maybe this time would be different. We weren’t in battle yet. The game was set up so that you had five years of in-game time to delegate stats and start a career path for your character, so that you could begin the war in whatever military or civilian position you wanted. There was also a default path, which I always ended up taking simply by not being lucid during the setup phase. The default was infantry, which also made it hard to find Brad, because he liked to fight in a more specialized role.

I waited to hear from the Air Force, and eventually got a letter saying I was admitted, and to show up for physical inspection at a nearby recruitment site. It was there that I saw Sarah. She was walking through the linoleum tiled hallway with a clipboard, stopping at each door and peering into it briefly before moving on, like one might do in an art gallery or a zoo. I wanted to look away, to force the apparition to dissipate, but I couldn’t help but stare. Maybe that was the cruelest part of all this. SimPharm used mostly prebuilt and composite personalities for it's sim-games. but when you signed up, you also signed away rights to the likenesses of people you knew, and it would use these to create NPCs in the games you played--likenesses with that kind of intimate connection were the most likely to create the kind of immersive experience they promised to their player base. Brad probably didn't think twice about her being here. About how SimPharm decided in a millisecond that the usefulness of his memory of her was as a clerk in a pencil skirt.

"Alright! Finally getting the hang of it, huh?" I felt a hand on my shoulder and turned to see Brad's new face looking down at me through short blond curls.  I wondered if the air-force allowed that haircut, or if the program fudged the rules like it did so many things to allow players to live out their perfect fantasies.

"Yeah, sorry if I'm bringing the team down."

"All good. I think I figured out how to get us into a jet day one. Follow my lead and then rev to graduation." He went to shake the hand of some old general walking by, introducing himself, and pointing to me. He walked right by not-Sarah. Didn't even flinch.

"I really need to talk to you about something. About Sarah" I said, once we were alone again.
"Oh, right. You were saying that before. Whats up? Kind of a weird place and time to talk about it though, don't you think?"
"Yeah. Long story. but listen, don't be alarmed, but she died."

His face changed. For the first time since we had started the game, it seemed like his momentum was slowing down.
"Oh, I'm sorry for your loss." he looked out into the distance, I figured he must be syncing with his Second Self, but I could only guess at what it was changing about his demeanor towards me. "Is that why you came out here? Asked for the invite."
I winced. This wasn't going how I had hoped--but how had I even hoped it would go? In any case, this was my chance.

"Yeah, kind of. Listen I know it was a long time ago that you guys broke up, and it's asking a lot of you, but I need help getting her Second Self shut down."

"Shut her down? Jesus. Why can't you do it?" I could feel something changing. The simulation started running slower around us. I was new to sim-games, but I got the feeling I was about to be told I was overstaying my welcome.
"I know, I'm useless at this stuff though, I just can't do it. You'd be doing me a huge favor, ok? Isn't that enough?"
I ended a little more exasperated than when I had begun speaking, and clearly he was not responding to that well. He again went dead-eyed, letting his Second Self run intention calculations on me, trying to figure out what I wasn't saying. But I wasn't not saying anything. that was why I had done it this way.
"Did she say something to you? about me?" he asked finally. His military recruit uniform was morphing into something else, a bionic enhanced jogging outfit.
"What?" I asked, "no, I just can't do it myself and you're the only person I could think of who might be able to help me?"
He looked at me in silence.
"Listen, I don't know exactly what's going on, but if we want to continue this conversation, I'm gonna have to insist we do it with eye-cams and law-fabs present. Standard pre-screen and everything, so there aren't any misunderstandings. If you came to me like this to bypass record-keeping, thats pretty low. I'm sure you mean well, but--"
"law-fabs? Pre-screen?" I yelled, "What are you talking about? I just want to get my dead sister out of the internet."
"I think you should go. It was nice seeing you again."

Before I had a chance to react, I was back in the Ex-Wraith loading zone, complete with elevator music and banner ads flashing across the screen.
"Shit." I said. I felt tired. It was three in the afternoon. My body was still in the factory for another four hours. There was nothing I could do but wait. I decided I might as well make use of the processing power I had. I clumsily moved through the manual motions to get the EX-Wraith to load my relationship profile with Sarah.
"Query. Brad Porter. "
Some lights flashed around me, and I could feel as well as hear the hum of the processor. It came back with a full readout of my second hand evaluation of Brad. Three years of a messy, early-twenties relationship summed up in a few lines:
Met at Rutgers College in Statistics of Bioengineering, room 304. In contact an average of 3.4 times a week for five years. Abrupt end to contact, notarized by SimPharm in coordination with Mirai Corp. less than one standard deviation away from norm for relationships of the same parameters.

I wanted to mope about the program summarizing a relationship to simply "within expectation," but then I noticed something odd about the computer's synopsis of Sarah's relationship. I went through my pers-com photo album to make sure, but as far as I knew Sarah and Brad had only dated for three years. This said they were in contact for five.
"Query. Last contact about Brad." Again, the processor hummed in my ear as it went through my collected data, made requests out to the network.
March 15th, 2065: Manual bypass was made on module to remove reference.

Now that was strange. I may not know how to articulate a SimPharm module, but I understood security mechanisms. As with most things close to the metal, that was my area of expertise. Old movies and books about high-tech worlds loved to depict hackers and cyber-criminals as something akin to samurai or cowboys. People with the skills and tools to move through the world in whatever way they wished, and often doing so to help the helpless or destroy the hubristic. With enough planning and know-how, a hacker could get through any system with the slinging of a few bits. In reality, most hacking has always been a process of social engineering. After all, if you want to break into a bank, what's easier: planting home-made dynamite to blow the three-inch thick steel door off, or lifting the key off the janitor? If someone performed a manual bypass, they would have at the very least, have had to gotten physical access to the device, and on that day it would have been right where it was right now: in my closet. I'd take a look at the device when I got home.
An ad for v-sex that promised 'discreet' usage of likenesses of whoever you wanted flew by. That kind of thing was obviously illegal, and the only reason they got away with it was probably because they sold the offender's info back to companies like SimPharm to do with as they wish, probably plummeting users into even more crushing debt than they were already in. That was one of the things that had pushed SimPharm into megacorp territory: streamlined and automated the justice system into an endless stream of fees and debts.

"Did you do anything to implicate Mirai Corp in your sister's death?" Dr. Singer said. I had come in right away the day after my failed meet-up with Brad, at her urgent prompting. My entire neck and back ached like I'd built a barn single handedly, and there were bruises all over my arms and legs, though nothing harsh enough to trigger the warranty I'd placed on my body when I signed it away to the sleepers.
"What? No I talked to Brad like I said I would and he wasn't interested."
"You did more than that, apparently. I *told* you that nothing good could come of trying to brute force this. You've just hit the worst case scenario. Brad worked at Mirai Corp with your sister. In different departments, but still, impressions have started to move through the social net, it could have a negative impact on internal company morale. "
"There was some misunderstanding, I wasn't trying to make Mirai Corp look bad. I didn't even mention them."
"But Brad *thought* you were implying something. Clearly. I was helping you pro-bono, since the company does so for all next-of-kin occurances after an employee passes. But this is beyond my pay-grade. I'm sorry, but I can't help you."
"Fine. What do I care anyway, if Sarah still has after images, She'll fade away from people's memory after a while anyway once she stops maintaining relationships."
"Oh, thats not what I mean, Mr. Strand." A small smile curled at the corner of her mouth.
"What?" I said.
"I mean that I can't help you if Mirai Corp seeks compensation from you for productivity loss. You know the laws, any reasonable grounds for lost revenue can be sought from the creator of the bad actor."
"compensation? and how am I supposed to pay for that?"
"If I'm not mistaken, Mr Strand, you did just sign a contract with the sleepers, did you not?"
My aching back throbbed.
"Yeah, I'm not going to keep doing that."
"I'm not sure you have a choice, Mr. Strand."

I could swear I could hear Dr. Singer laughing when I left her office on the fourtieth flour and made my way to the elevator, back to the city streets below.


Suddenly I had a lot of free time on my hands, stuck in a sort of digital purgatory. Every day I woke up and tried to recover some mobility in my body, doing kalisthenics and stretched I had learned in high school. I tried to eat better, and use what little amount of money left over from my salary and the money I got from the sleeper comp deal after Mirai had had their hands in my pockets on real organic protein. None of it mattered. I could feel my body wasting away. The strangest part of it all was the free time. Everything was going to shit, but I had almost twelve hours a day with absolutely nothing to do but watch ads fly by, or else pay for subscription service games and immersive programs. I ignored the constant togs at my most indulgent urges and focused on Sarah instead. being plugged in so long I was actually learning the articulors for the first time in my life. Eventually I was able to do a reverse scan on all the info I had about March 15th 2065. I hadn't remembered the day at first, when it showed up in my search, because nothing important had happened on that day. Sarah had come over, as she used to do, to complain about how messy my apartment was, and to beg me to come out with her somewhere or other, to Navy Pier or to Millenium Park. Get outside for a bit. But somewhere during that visit. She asked about Brad. It was so perfectly curated as a moment of intentional aloofness. She just asked if I remembered him. I had said "yes, he was a jerk, in the end, wasn't he." She had agreed. And then, while I was in the bathroom, she had opened the server's tiny closet. She had given it to me, so she already knew the password--I had never changed it. And that was it.

I never found out what happened between her and Brad. But maybe that was how it was supposed to be. I liked to think that I stayed unplugged for so long because of some sort of romanticism. That I liked when things were more real, more authentic. But that wasn't true. I was somehow more a recluse than the kinds of people who spent their whole lives online. The truth is that I was scared of sinking in. Maybe Sarah had known that too, and that was why she gave me the beater of a Mirai that couldn't do much other than keep voice memos. Now, stuck in permament ad-space, I understood. The activator for going to the home-menu, it was linked to whatever feeling was most linked to comfort for you, to belonging. For me, that was being in alone, in a room just outside the action. Disassociated.

Sarah had been different. She had wanted to participate. and no one would ever know what happened to her. I didn't know what happened to her. For god's sake, I had never even asked how she died. But know people would know. At least they would know that she had existed. The thing about after-images, the reason Mirai was willing to pay law-techs to weed them out, is that they made people uncomfortable, brought up questions they didn't want people asking. Now, almost every eye-tech in the city was wired to recognize her in the street, force the user to do a search, wondering if she were a celebrity, or a famous sports-star, or someone they knew from college. And they would hear about my sister, Sarah, recently deceased. and right by her name: Mirai Corp.

I heard a knock at the door. I imagined being in a bathroom, with pop music playing just on the other side of the door, and drifted away.
