#+title: Self-Help



The world is a harsh place, no one can deny that. But it is also fair, definitionally fair. What could be more fair than the way things naturally are. That’s the baseline. We’ll circle back to that soon. I’m Annalise Taylor, I don’t have many credentials you’d usually find from the authors of books like this. I’m taking a different approach. You might have opened How to Escape the Underworld and assumed I’d already done it. That I’m a self starter entrepreneur, a brainy inventor, or a shrewd businesswoman who started in the mailroom and made every right decision needed to make it to the top. Well, I have worked in a mail-room, but I didn’t get anywhere from there. I’m actually still in the underworld at the time of writing this. And I’m only thirteen years old. I decided this week that I have ambitions, and the only stuff I could find online about how all the awesome kick-butt topsiders get to live is books my mom had, she calls them ‘self-help’. I read a bunch of them and I realized there was uncharted territory in the canon of self-help educational literature: the perspective of the before. I want to show you the steps I take to get to success, all the way from here, sitting in the shadow of the Greater Chicago Overpass.

Now you might be saying, how do I know I’ll be successful? Well I don’t——but I do. And I will be. These entries will be going up to my personal blog, which as of now is set to private. Someday I’ll flip the switch and every entry will be collected into a book about my path to the top, and beyond. What I collect here is that journey. So if you are reading this, I did make it. But I won’t know it till I get there. Enjoy the ride.

* Beginnings
Every great self-starter has humble beginnings, and mine certainly are humble. Chicagoland isn’t what it used to be, at least that’s what dad says. Some  incredible entrepreneurs (who have written their own self-help books)like Stephen Marks were able to get education out of the hands of corrupt politicians, thank GOD. Dad says politicians are the worst kinds of liars, they’ll tell you they’re on your side and then BOOM, all your money and your freedoms are gone. Dad says freedoms are the things you could do if you wanted, but most people don’t do them. They’re still freedoms even if you don’t use them. Unfortunately, many neighborhoods, such as my own of East Aurora, couldn’t make the minimum payments to maintain a charter school. That means kids have to enter bids for scholarship seats in the nearby school districts.

And that brings me to what I’m calling Annalise’s Rules for Success. Lesson number one: How early did you know? I knew right away. As far back as I remember, I knew I wasn’t going to end up like the derelicts in the streets. When I see them on my way to the park, I always crossed to the other side first, and I don’t even look at them. If I look at them, I can smell them, even if they aren’t close. It’s like a smell in my mind. I didn’t know why then, but even as a little girl I had the sense that I was upset with them for making me see their sorry state—and how right I was. Not everyone is cut out for the big leagues. If you don’t know by the time you’re five, then you might not make it into the top 2% of test scores necessary to get a seat at a school like Lower Naperville K-12. Maybe you’re lucky enough to have a school with better entry numbers—but there are still kids who would have made the cut with thinner margins, and that reality will only take longer to settle in. Trust me.

So yeah, lesson one: Know you are meant for success right away, and never doubt it.

* Make Your Mark
Now if you live in an underground like I do, there’s a good chance you don’t have great access to modern tech, and that is going to hurt your ability to succeed—and we can’t have that! At a nicer district, kids would start taking data-plus literacy classes around my age. This is to set them up for receiving their own personal data-plus device, so they can go on to take more advanced subjects in stride, like Calculus, Global Language, and Sociologics.

You might look around yourself at thirteen, like I am now, and realize that everyone you know and have grown up with will slowly fall behind as kids with access to better materials, kids you know are not innately smarter than you are, continue to flourish. I call it the Law of Jessica. Jessica is a girl I met at a track meet last year. She’s from a topside neighborhood. I played her in soccer like three years ago and she was scrawny and uncoordinated. Now she’s a top athlete and I couldn’t stand a chance in the 400m. Anyone’s natural inclination is to coast through life and just use whatever is given to them, I definitely was like that last year. But for some people, that ‘coasting’ is just gonna get you to a better place. Like Jessica. We can’t have that. So, if your school can’t afford data-pluses for everyone, you might decide to pool money together for one that everyone can use. You might hope that everyone in your class could get a chance to try it out, learn how to let it sync with your brain, feel the euphoria of heightened senses and memory capacity. Think of all the work you could accomplish if you had one all to yourself! Now the unfortunate reality of scarcity rears its head once again. How many kids are in your class? How do you decide who gets to use the data-plus, and how often? Whose parents paid into it, and who’s couldn’t even afford a fraction?
Well, it’s time for lesson two: The world will bend to your will, as long as you play by its rules. Like I said, everything in this world is fair—but that doesn’t mean everything is just. You may want everyone to move forward together, you might have friends, Like I had Jack, and Penelope, and Mateo, and Guava. Maybe you have a Jack, a fierce personality, a beautiful mind for business, and a natural way with words. My Jack was a great talker. He had brown hair that he plastered to his head, but that I knew secretly was an unruly mess right out of the shower. Whether he was talking you into truth-or-dare, or talking the parents into paying for his car wash (an old rag and some water dyed blue in an old squeeze bottle). Maybe your Jack, like mine, has a voice that’s both sweet and firmly convincing—I would have bought anything he was selling. But Jack’s parents couldn’t pitch in, on account of his dad being dead and his mom being in jail for missing her rent too many times. So even though we only had a data-plus because of Jack’s smooth-talking, the parents and teachers were pretty much in agreement that he didn’t get a turn.
If you have a Jack, you have to stay strong. The world is fair. Remember that. You can tell your Jack what I told mine. That you’d come back, that once you get to the top, you’ll be at the reigns, and one of the many philanthropic endeavors you’ve begun listing in your nighttime journal will be to start a new charter school, one that gives every kid a chance. You can tell your Jack that once you have the power to change what’s fair, you’ll make it so kids like him get what they deserve. What’s fair isn’t just, but it doesn’t have to stay that way.

* How Far are you Willing to go?
Annalise, here again with more Self-Help tips! I’ve made do with a communal data-plus for four years, and if you’re anything like me, some issues have started to crop up. See, as you might know, the data-plus is meant to be a personal use device. It wasn’t built to be used by more than one individual. And eventually you’ll get to the age I’m at now, where the tech kicks in with its ability to maintain relationships—personal and professional—and helps you specialize according to your talents. But, uh oh, you probably won’t be lucky enough to all have the same talents, or keep the same friends and colleagues. It might look like it’s finally going to start happening—those with the resources will coast on ahead while you slow down. Damn that Jessica! But don’t worry, It’s time for lesson three. Up till now, it’s all been about just you, you at the expense of others. You have to run the quickest, study the hardest, work the most shifts at the factory on Delaney that lets kids work part-time, long as their parents sign a slip. But now, It looks like only one out of ten or twenty will make it out, and how could you possibly decide? And even if you tell the other nineteen kids what you told Jack, will they even accept it? Would you accept it, if it came down to one arbitrary point on a math question between you and the winner? Well, you probably would, because the world has its rules, and as we know the best way forward is not to move against them, but to redirect their energy. Anyway, It’s a false dichotomy (that means you think there’s two answers but there’s really more than that).
You were willing to sacrifice your friends for the chance at success, but are you willing to sacrifice yourself? The answer is obvious. Those who move forwards are those willing to melt their personalities, their wills, their intentions, into a single pot. You all have similar goals, and you can function even better as the body parts of a larger, more productive super-body! It’s like those robot anime shows Jack used to watch, when he still talked to me. You might decide on some level of ceremony for this transition, away from parental supervision—such as the abandoned football stadium left to decay under the superhighway that runs all the way to the Rockies, and which you’ve only been on once, during an evacuation drill. You might decide on some sort of team building rituals, like workshopping your new collective persona’s name, age, sex, ethnicity. You might want this new person to be an averaging of all your constituent identities—so long as there aren’t so many that it becomes confusing. Try to make sure everyone is included, but if anyone doesn’t like the decisions, they should know the only option is to leave the group. We had twenty kids in our class using the data-plus, but only ten ended up being our new supergroup, ten is probably a good number to aim for. Once it’s all decided, you have learned lesson three: Your ambitions are more important than your individuality. Remember, the goal is to change the natural fairness of the world into something you prefer. Once you’re at the top, you will be able to make change, but right now, you have to play the game in whatever way you can. Once you have some money and power, you might be able to make a cheaper, more economic version of a data-plus that any family could afford, or even give them out yourself in the underground neighborhoods across America. You might make it so that there’s a version of the data-plus designed to be used by a community, so that people don’t have to pretend they aren’t from their own families, or that they are in love with someone they aren’t. But all that is down the road—it’s like Stephen Marks says in his self-help book: always look forward.

* Career is King
Annalise here. I can’t believe I started this project almost eight years ago. I always knew things would work out, and you should too! It hasn’t been easy, obviously. Let me explain some specifics. If you’ve been following my advice and all goes according to plan, you’ll find yourself at a new roadblock before you know it: a real-deal professional career. Depending on how good your super-group is as a unit, you might make it to one of the sponsorship colleges, with a guarantee of a corporate job on the other side. If you manage this, it is natural to feel nervous about your presence as an imposter, about how your version of reality is different to those you interact with. You might even feel like you are doing something wrong. Don’t worry, I’m here too, and I can teach you lesson four: The right thing to do is always what helps productivity. If you’re anything like me, you might realize that, at this point, your super-group isn’t just performing at the same level as your single-personality colleagues, you’re performing better than them. How could what you are doing be wrong if you’re at the top of the class? And for the same price, mind you. It isn’t exactly ideal to be splitting an entry level salary ten ways. So remember rule number one, and keep pushing. You’re already on your way.

----

A hard truth is that challenges are only challenging when you don’t see them coming, so I’m going to share an experience of a challenge we didn’t see coming. If you run into a similar situation, know that it isn’t over. Trust the process.
Our super-group has been running at full efficiency for five years, and getting steadily promoted all throughout that time. Our chosen avatar met in person with the CEO of the company (which I won’t name for legal reasons, but just know they have quite a lot to do with peace in the mid-east, and his name ends with -arks) and it seemed to be going great, until something unexpected happened. They noticed our data-plus. An old model, they said. Why don’t you get an upgrade? They asked. We didn’t have an answer. They wanted us on a new job, high level, chance for upward mobility, they said. We’d love to, we said, hoping they forgot the data-plus issue. They didn’t. Go to the in house physician, they said. Get your readings done, they’d get you on the latest model as a business expense. Sure thing, we said. Only it wasn’t a sure thing. We didn’t have just one reading to get done, we needed ten, and what would the physician say if they looked at the reading on the old data-plus. Would they tell the boss that they were paying ten people for one person’s job? That our sob story about being from the underground was just that—a story, and that we were trying to pull a fast one? So here’s lesson five: not everyone thinks the way you do, you have to be willing to compromise, and to adjust.

Now, I am a firm believer that discrimination is wrong, in some cases. Discrimination based on any metric that doesn’t directly correlate to the thing being measured or analyzed should not be accounted for. However, discrimination is ok if the factor is relevant to the query. In fact, such discrimination is the point of any analysis. So while I would never judge someone who didn’t come from the underground as inferior to myself, or as having less talent innate in them, I can say that they haven’t had the experiences I’ve had. They haven’t been forced to see the way the world is brutally fair, cruelly so. They wouldn’t understand right away if I tried to explain our situation to them, and you might have a similar conundrum. Being aware of these differences of perspective is one of the many keys to success. In the same way that topsiders might not know or agree with what ugly things you had to do to get here, they also haven’t had to live every day like it was their last, like it was life or death. So they won’t be suspicious if you slip a device into a physicians office to get into their computer, to create an alias for your ten readings, which you got done for a little extra cash from a third party, and created a trigger to automatically override the avatar’s readings with the averaged out one. For people who aren’t always on guard there is nothing in their daily lives that is capable of harming them—and that’s just the fairness of the world at work once again. If you manage to get topside someday, you might have kids who grow up like that—not wondering where their next meal comes from, not losing friends to factory accidents or gang violence. Not afraid or angry at the people they pass on the street, wondering if they’re intoxicated or crazy. The world is what you make it, so it will always be fair.


* Making it isn’t the end
Annalise here. I can’t believe I ever made these, or that I keep them. I was so naive back then. But I guess I’m still naive. Might as well finish he job. If anyone has been dumb or foolhardy enough to follow my path, congrats—you’ll become one of the people in the room (secretly, a group of people) who are asked to give the OK anytime a decision is made. You may realize that at this level, you aren’t at the top of the class anymore—but you’ll think that’s just proof that competition works. You might, as I did, marvel at the ability of the individual, with proper resources, to compete with a group who have worked as a unit for almost their whole lives. You’ll start having the chances to make the world just, not only fair, but just.

But you’ll realize it isn’t that simple. Those moments will happen in board rooms, and in emails, with eyes and opinions from prospective clients, and politicians, and colleagues. You’ll have agency in theory, but any of that agency that you use in a way that doesn’t fit the expectation of you will raise eyebrows, and might result in you not getting as much agency in the future. You may realize, with the horror that I did, that you are feeling this way both as a collective, and within your collective. That you decided on a path forward decades ago, and that none of you have really been in the driver seat in a long time, like you had been playing your lives like an ouija board. You might wonder what demon or spirit you had conjured up, and you’d only think about the world, about that truth you’ve whispered to yourself since you were a little girl, since you told Jack, weeping, his head on your chest, that you’d come back for him.

Maybe, if you make it as far as I did, you’ll come to the point that the world really does reveal itself to you. You’ll be privy to conversations that are intentionally not recorded, to quips and derisions that you are appalled to hear from the people you dreamed of sharing a table with for so many years. You might find out that not all of the defense capabilities your company manufactures are going to help build better, more just governments abroad, but are being used within your own country, to control the interests of the company and it’s allies. You might find out that the corporations have intentionally destroyed the fabric of government keeping the country together, albeit tenuously, so that they could act with impunity. You might realize the underlying philosophy was no different than what brought you into those rooms, after so much fighting and climbing. You might hear in passing that there have been rumors of a competing service using the same methods as the data-plus the company sells to corporations across the globe. You might realize with some relief that you have the authority to ask for details. You might wish you hadn’t asked, when you learn that the best data-plus units on the market aren’t computers at all, but remote workers. That everyone in the room with you at the top has a team two or three times the size of your super-group, in India or in Ukraine, all working to keep their individuality competitive. You might, trying to keep your avatar’s voice flat, ask where the competitor is located. And If you haven’t kept careful cover of your tracks, you might find out that they located a bloc of group-cells in the neighborhood you came from. You could mention that you are from there to drive off suspicion rather than garner it if they find out on their own. But even if you miss that maneuver, it’s likely they won’t catch on. Even if they did, you work with them—work for them. You might think for a moment if there is anything you can do, isn’t this the kind of thing you always said you’d be able to steer towards justice, if you got here? But you’ll look around and realize that your authority only exists insofar as it is used to an aim this room agrees with.

If you are reading this, I hope you can learn something from my experiences. It wasn’t easy getting where I am, and neither I nor anyone in my super-group have any regrets. I timed this website to release, and be hosted on different mirror sites across the globe so the company has a harder time shutting it down. My group broke up. Some of us came back to East Aurora, so that we could be here when the bombs dropped. But the others are free now to decide what justice means for themselves. I’m writing this from my childhood home. The complex across the street, where Jack used to live, has been demolished and replaced with an elevator topside. The last lesson in Annalise’s rules for success: You are always free to decide what success means for yourself.
